# Pre-commit hooks for Claude Observability Hub
# Install: pip install pre-commit && pre-commit install

repos:
  # Python hooks
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.11
        files: ^templates/.*\.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        files: ^templates/.*\.py$
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
      - id: mypy
        files: ^templates/.*\.py$
        additional_dependencies: [types-requests]

  # JavaScript/TypeScript hooks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx|vue)$
        types: [file]
        additional_dependencies:
          - eslint@8.50.0
          - '@typescript-eslint/eslint-plugin@6.0.0'
          - '@typescript-eslint/parser@6.0.0'
          - 'eslint-plugin-vue@9.17.0'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|vue|json|yml|yaml|md)$
        exclude: ^(coverage/|dist/|node_modules/)

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: detect-private-key

  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: ['--fix']

# Local hooks
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c 'cd "$(dirname "$0")/../.." && python -m pytest templates/hooks/.claude/hooks/tests/ -x --tb=short'
        language: system
        files: ^templates/.*\.py$
        pass_filenames: false

      - id: no-debug-statements
        name: Check for debug statements
        entry: bash -c 'grep -r "debugger\|console\.log\|print(" --include="*.py" --include="*.js" --include="*.ts" --include="*.vue" . || true'
        language: system
        pass_filenames: false