version: '3.8'

services:
  devcontainer:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment:
      - NODE_ENV=development
    network_mode: host  # Simplifies port access during development

  hub:
    build: ./core/server
    container_name: observability-hub
    ports:
      - "4000:4000"
    volumes:
      - ./core/server:/app
      - hub-data:/data
    environment:
      - DATABASE_URL=sqlite:///data/events.db
      - NODE_ENV=development
    command: bun run --watch src/index.ts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 5s
      timeout: 3s
      retries: 5

  dashboard:
    build: ./core/dashboard
    container_name: observability-dashboard
    ports:
      - "5173:5173"
    volumes:
      - ./core/dashboard:/app
      - /app/node_modules  # Preserve node_modules
    environment:
      - VITE_API_URL=http://localhost:4000
      - VITE_WS_URL=ws://localhost:4000/stream
    command: npm run dev -- --host
    depends_on:
      - hub

volumes:
  hub-data: